-- Run this in Supabase Dashboard > SQL Editor.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  price bigint not null check (price >= 0),
  category text not null default 'Other',
  image_url text,
  description text not null default '',
  available boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.products enable row level security;
drop policy if exists "Anyone can read available products" on public.products;
create policy "Anyone can read available products" on public.products for select using (true);
drop policy if exists "Signed-in admins can insert products" on public.products;
create policy "Signed-in admins can insert products" on public.products for insert to authenticated with check (true);
drop policy if exists "Signed-in admins can update products" on public.products;
create policy "Signed-in admins can update products" on public.products for update to authenticated using (true) with check (true);
drop policy if exists "Signed-in admins can delete products" on public.products;
create policy "Signed-in admins can delete products" on public.products for delete to authenticated using (true);
